### ISSUE TITLE
columns and bars cannot be reversed when they are not stacked.

### ISSUE THREAD

**Issue by msberends** [msberends/certedata#15]

**Comment by michellymenezes** [comment]
Where is this error happening? Can you show me the file?

**Comment by msberends** [comment]
No I cannot, because this is only a repository for employees of Certe. You are allowed to view and fork the code, but as you can read in the LICENSE file, you do not have permission to use, share or modify the software.

**Comment by msberends** [comment]
I’m sorry :)

**Comment by msberends** [comment]
Please consider all issues in this project as a **note to self**, for me as developer.
